version: "3"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80/tcp"
      - "8443:443/tcp"
    volumes:
      - "./app/:/var/www/html"
      - "./nginx.site.conf:/etc/nginx/conf.d/default.conf"

  php:
    build:
      dockerfile: Dockerfile-php
      context: .
    volumes:
      - "./app/:/var/www/html"
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
