version: "3"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80/tcp"
      - "8443:443/tcp"
    volumes:
      - "./app/:/var/www/html"
      - "./.docker/nginx.site.conf:/etc/nginx/conf.d/default.conf"
    restart: unless-stopped

  php:
    build:
      dockerfile: Dockerfile-php
      context: .docker
    volumes:
      - "./app/:/var/www/html"
      - "./.docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
    environment:
      - DB_USERNAME=$DB_USER
      - DB_PASSWORD=$DB_PASS
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - "POSTGRES_USER=$DB_USER"
      - "POSTGRES_PASSWORD=$DB_PASS"
      - "POSTGRES_DB=$DB_NAME"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - "PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL"
      - "PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD"
      - "PGADMIN_DISABLE_POSTFIX=$PGADMIN_DISABLE_POSTFIX"
      - "PGADMIN_LISTEN_PORT=$PGADMIN_LISTEN_PORT"
      - "PGADMIN_CONFIG_LOGIN_BANNER=$PGADMIN_CONFIG_LOGIN_BANNER"
    restart: unless-stopped

  redis:
    image: redis:7
    restart: unless-stopped

volumes:
  db-data:
